setup:
  python_version: '3.8'  # O la versión de Python que estás utilizando
  build:
    - python3
    - gcc

services:
  app:
    build:
      - python3
      - gcc
    run:
      - python -m venv --copies /opt/venv && . /opt/venv/bin/activate
      - pip install -r requirements.txt
      - nixpacks build main.py --port $PORT
